### ISSUE TITLE
Found an error in the dotfiles repo tutorial

### ISSUE THREAD

**Issue by programmeuris** [ecarlson94/dotbot-template#2]
In the dotfiles repository tutorial, step 6 and 7 under 'making it your own' instruct people to name a file 'zsh.yaml', resulting in an error given that they're both in meta/configs. I believe that the intention was to name the second file 'alacritty.yaml'. It's very minor, but since the page is a tutorial I figured you'd want to correct it.

![firefox_d8GjGYCVqR](https://user-images.githubusercontent.com/52523691/113729012-e69b7100-96f6-11eb-9b5a-b321c285062b.png)

**Comment by kiriwalawren** [comment]
Thank you for catching this, @programmeuris! I'll get this fixed up right away.

Edit: You having pointed this out showed me another error in that step. So thanks again.

**Comment by kiriwalawren** [comment]
The content of step 7 was wrong as well. Alacritty expects an `alacritty` folder inside `~/.config`. So, the content needed to be:
```diff
-  $HOME/.config: alacritty
+  $HOME/.config/alacritty: alacritty
```
I have fixed both issues.
